# Generated by Django 4.0.6 on 2022-08-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True, max_length=150)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
