# Generated by Django 4.0.6 on 2022-08-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
